### PR TITLE
DUN-150

### LINKED ISSUE #150: Text Transform Property not working
**Describe the bug**
Text transform property in Text and TextArea is currently applying no effect.

**Expected behavior**
Upon using the Text Transform property, the text introduced should change according to the selected transform in the dropdown provided.

### PR DESCRIPTION
**Pull request by TinCodes**
Text Transform now working properly + minor fixes in DateTime

### CODE REVIEW

File: vue2-vuetify/src/dynaform/DynaformStringControlRenderer.vue [hunk 1]
```diff
@@ -52,11 +52,7 @@
           :persistent-hint="persistentHint()"
           :required="control.required"
           :error-messages="control.errors"
-          :value="
-            control.data
-              ? control.data
-              : control.uischema.options.defaultValue || ''
-          "
+          v-model="textValue"
```
Comment (fagubla) [inline vue2-vuetify/src/dynaform/DynaformStringControlRenderer.vue]: why are you using v-model instead of :value?
Another field controls are using :value

File: editor/src/components/DynaformPreview/mainPanelDynaformPreview.vue [hunk 2]
```diff
@@ -132,18 +132,18 @@ export default {
...
+      //   this.$store.get('app/editor@schema')
+      // );
+      // this.$store.dispatch(
+      //   'preview/setUiSchema',
+      //   this.$store.get('app/editor@uiSchema')
+      // );
+      // this.$store.dispatch(
+      //   'preview/setLocale',
+      //   this.$store.get('app/jsonforms@locale')
+      // );
```
Comment (fagubla) [inline editor/src/components/DynaformPreview/mainPanelDynaformPreview.vue]: remove the code commented

**Review by fagubla — DISMISSED** [review]

**Review by fagubla — APPROVED** [review]
