### PR TITLE
Templates and component types now working correctly

### LINKED ISSUE #101: Templates not working with new Component Types
**Describe the bug**
When using a template, a conflict between types emerges and renderers are not picked correctly. Configuring the types of each component in each template can solve this issue.

**Expected behavior**
When using a template, each component in the form is being rendered correctly in the preview and the editor.

### PR DESCRIPTION
**Pull request by TinCodes**

### CODE REVIEW

File: vue2-vuetify/src/editor/RatingControlRendererEditor.vue [hunk 1]
```diff
@@ -5,24 +5,6 @@
     :isFocused="isFocused"
     :appliedOptions="appliedOptions"
   >
-    <!-- <v-text-field
```
Comment (hjonathan) [inline vue2-vuetify/src/editor/RatingControlRendererEditor.vue:8]: Please remove comment code

File: vue2-vuetify/src/editor/DropdownControlRendererEditor.vue [hunk 2]
```diff
@@ -83,6 +77,25 @@ const controlRenderer = defineComponent({
...
   },
+  computed: {
+    hint(): string {
+      return this.control.uischema.options?.hint ?? '';
+    },
+    placeholder(): string {
+      return this.control.uischema.options?.placeholder ?? '';
+    },
+    items(): string[] {
+      console.log(this.control.schema.enum);
```
Comment (hjonathan) [inline vue2-vuetify/src/editor/DropdownControlRendererEditor.vue]: remove the console.log

**Review by hjonathan — APPROVED** [review]
