### PR TITLE
Preview renderers for all available components working

### LINKED ISSUE #99: Preview Renderers not working
**Describe the bug**
When placing components from the editor palette to the form and then going into 'Browser' or 'Preview' mode, no renderer is found for any component.

**Expected behavior**
If a component is placed into the Main Panel then when entering Preview mode, a renderer of that component is shown too.

### PR DESCRIPTION
**Pull request by TinCodes**

### CODE REVIEW

File: vue2-vuetify/src/dynaform/DatePickerControlRenderer.vue [hunk 1]
```diff
@@ -0,0 +1,108 @@
...
+  setup(props: RendererProps<ControlElement>) {
+    return {
+      ...useVuetifyControl(useJsonFormsControl(props)),
+      menu: false,
+      date: null,
+    };
+  },
+  computed: {
+    setDefault(): string {
+      return '1992-01-29';
```
Comment (fagubla) [inline vue2-vuetify/src/dynaform/DatePickerControlRenderer.vue]: Remove hardCode

File: vue2-vuetify/src/dynaform/MultipleFileControlRenderer.vue [hunk 2]
```diff
@@ -0,0 +1,151 @@
...
+        </v-list-item-action>
+        <v-list-item-action>
+          <v-btn icon @click="deleteFile($event, i)" align="right">
+            <v-icon color="grey lighten-1">mdi-delete</v-icon>
+          </v-btn>
+        </v-list-item-action>
+      </v-list-item>
+    </v-card>
+
+    <!-- </template> -->
```
Comment (fagubla) [inline vue2-vuetify/src/dynaform/MultipleFileControlRenderer.vue]: remove comment

File: vue2-vuetify/src/dynaform/RatingControlRenderer.vue [hunk 3]
```diff
@@ -0,0 +1,96 @@
+<template>
+  <control-wrapper
+    v-bind="controlWrapper"
+    :styles="styles"
+    :isFocused="isFocused"
+    :appliedOptions="appliedOptions"
+  >
+    <!-- <v-text-field
```
Comment (fagubla) [inline vue2-vuetify/src/dynaform/RatingControlRenderer.vue]: Remove code commented

**Review by fagubla — APPROVED** [review]
